spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: redirect_auth
          uri: lb://AUTH-SERVICE
          order: 0
          predicates:
              - Path=/auth/**
          filters:
              - StripPrefix=1
              - RedirectTo=302,http://AUTH-SERVICE/envInfo/target
        - id: simple_auth
          uri: lb://AUTH-SERVICE
          order: 0
          predicates:
              - Path=/simple-auth/**
          filters:
              - StripPrefix=1

server:
  port: 6145
eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug