spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: test_eureka_service
          uri: lb://AUTH-SERVICE
          order: 0
          predicates:
              - Path=/auth/**
          filters:
              - StripPrefix=1
              - RedirectTo=302,http://AUTH-SERVICE/envInfo/target

server:
  port: 6145
eureka:
  client:
    service-url:
      defaultZone: http://registerCenter:abc123456@192.168.3.137:8788/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug